from __future__ import annotations

from typing import Any, Optional, Tuple

def backend_name() -> str: ...
def is_ready() -> bool: ...
def scil_step_json(
    state_json: str,
    instr_json: str,
    binder_json: str,
    py_bus: Any,
    pre_json: Optional[str] = None,
) -> str: ...
def execute_bound_repr(state_json: str, bound_json: str, py_bus: Any) -> str: ...

class CPU:
    def __init__(self, memory: Any, *, reset_on_init: bool = True) -> None: ...
    def execute_instruction(self, address: int) -> Tuple[int, int]: ...
    def power_on_reset(self) -> None: ...
    def read_register(self, name: str) -> int: ...
    def write_register(self, name: str, value: int) -> None: ...
    def read_flag(self, name: str) -> int: ...
    def write_flag(self, name: str, value: int) -> None: ...
    def snapshot_cpu_registers(self) -> Any: ...
    def load_cpu_snapshot(self, snapshot: Any) -> None: ...
    def get_stats(self) -> dict[str, int]: ...

class Runtime:
    def __init__(self, memory: Any, *, reset_on_init: bool = True) -> None: ...
    def power_on_reset(self) -> None: ...
    def execute_bound_repr(self, bound_json: str) -> None: ...
    def read_register(self, name: str) -> int: ...
    def write_register(self, name: str, value: int) -> None: ...
    def read_flag(self, name: str) -> int: ...
    def write_flag(self, name: str, value: int) -> None: ...
    def snapshot_json(self) -> str: ...
    def load_snapshot_json(self, payload: str) -> None: ...
    @property
    def halted(self) -> bool: ...
    @halted.setter
    def halted(self, value: bool) -> None: ...
