#!/usr/bin/env python3
"""Bundle the PC-E500 web frontend modules into static/app.js."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STATIC_DIR = ROOT / "static"
SRC_DIR = STATIC_DIR / "js"
OUTPUT_FILE = STATIC_DIR / "app.js"

MODULE_ORDER = [
    "core.js",
    "pc_address.js",
    "keyboard.js",
    "ui.js",
    "main.js",
]

HEADER = """// This file is generated by scripts/build_frontend.py.
// Do not edit directly; update files under static/js/ instead.
"""


def main() -> None:
    lines = [HEADER]
    for relative in MODULE_ORDER:
        module_path = SRC_DIR / relative
        if not module_path.exists():
            raise SystemExit(f"Missing module {module_path}")
        lines.append(f"// >>> {relative}")
        lines.append(module_path.read_text())
        lines.append("")
    OUTPUT_FILE.write_text("\n".join(lines))
    print(f"Wrote {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
