// PY_SOURCE: sc62015/pysc62015/instr/opcode_table.py
//! Opcode table scaffolding for LLAMA.
//!
//! This mirrors the structure of `sc62015/pysc62015/instr/opcode_table.py`
//! without the LLIL/SCIL layers. Populate `OPCODES` by transcribing the Python
//! definitions (mnemonic/name, condition, operand list, optional reversed
//! order). Kept separate so the evaluator can consume a structured table.

#![allow(dead_code)]

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RegName {
    A,
    B,
    BA,
    IL,
    IH,
    I,
    X,
    Y,
    U,
    S,
    F,
    PC,
    FC,
    FZ,
    IMR,
    Temp(u8),
    Unknown(&'static str),
}

#[derive(Debug, Clone, Copy)]
pub enum RegImemOffsetKind {
    DestImem,
    DestRegOffset,
}

#[derive(Debug, Clone, Copy)]
pub enum OperandKind {
    Reg(RegName, u8),
    Imm(u8),
    ImmOffset, // signed relative offsets
    IMem(u8),
    EMemAddr(u8),
    EMemReg(u8),
    EMemIMem(u8),
    EMemImemOffsetDestIntMem,
    EMemImemOffsetDestExtMem,
    EMemRegModePostPre, // placeholder for EMemReg with mode constraints
    EMemAddrWidth(u8),
    EMemAddrWidthOp(u8), // EMemAddr with trailing IMEM operand (offset forms)
    EMemRegWidth(u8),
    EMemRegWidthMode(u8), // EMemReg with mode constraints
    EMemIMemWidth(u8),
    IMemWidth(u8),
    RegPair(u8),
    RegIMemOffset(RegImemOffsetKind),
    RegB,
    RegIL,
    RegIMR,
    RegF,
    Reg3,
    Unknown(&'static str),
    Placeholder,
    ImemPtr, // generic IMEM pointer selector (e.g., Reg3)
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InstrKind {
    Nop,
    Ret,
    RetI,
    RetF,
    JpAbs,
    JpRel,
    Pre,
    Mv,
    PushU,
    PopU,
    PushS,
    PopS,
    Unknown,
    Add,
    Sub,
    Adc,
    Sbc,
    Pmdf,
    Mvl,
    Sbcl,
    Cmp,
    Test,
    Xor,
    Inc,
    Dec,
    And,
    Or,
    Sc,
    Rc,
    Ex,
    Exl,
    Dadl,
    Cmpw,
    Cmpp,
    Mvw,
    Mvp,
    Mvld,
    Dsbl,
    Ror,
    Rol,
    Dsll,
    Dsrl,
    Shr,
    Shl,
    Swap,
    Wait,
    Halt,
    Off,
    Tcl,
    Ir,
    Reset,
    Call,
}

#[derive(Debug, Clone, Copy)]
pub struct OpcodeEntry {
    pub opcode: u8,
    pub kind: InstrKind,
    pub name: &'static str,
    pub cond: Option<&'static str>,
    pub ops_reversed: Option<bool>,
    pub operands: &'static [OperandKind],
}

/// Synced from sc62015/pysc62015/instr/opcode_table.py via
/// `uv run python scripts/generate_llama_opcodes.py`.
pub static OPCODES: [OpcodeEntry; 256] = [
OpcodeEntry {
        opcode: 0x00,
        kind: InstrKind::Nop,
        name: "NOP",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0x01,
        kind: InstrKind::RetI,
        name: "RETI",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0x02,
        kind: InstrKind::JpAbs,
        name: "JP_Abs",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Imm(16)],
    },
    OpcodeEntry {
        opcode: 0x03,
        kind: InstrKind::JpAbs,
        name: "JPF",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Imm(20)],
    },
    OpcodeEntry {
        opcode: 0x04,
        kind: InstrKind::Call,
        name: "CALL",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Imm(16)],
    },
    OpcodeEntry {
        opcode: 0x05,
        kind: InstrKind::Call,
        name: "CALLF",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Imm(20)],
    },
    OpcodeEntry {
        opcode: 0x06,
        kind: InstrKind::Ret,
        name: "RET",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0x07,
        kind: InstrKind::RetF,
        name: "RETF",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0x08,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x09,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegIL, OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x0A,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::BA, 16), OperandKind::Imm(16)],
    },
    OpcodeEntry {
        opcode: 0x0B,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::I, 16), OperandKind::Imm(16)],
    },
    OpcodeEntry {
        opcode: 0x0C,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::X, 24), OperandKind::Imm(20)],
    },
    OpcodeEntry {
        opcode: 0x0D,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::Y, 24), OperandKind::Imm(20)],
    },
    OpcodeEntry {
        opcode: 0x0E,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::U, 24), OperandKind::Imm(20)],
    },
    OpcodeEntry {
        opcode: 0x0F,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::S, 24), OperandKind::Imm(20)],
    },
    OpcodeEntry {
        opcode: 0x10,
        kind: InstrKind::JpAbs,
        name: "JP_Abs",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(20)],
    },
    OpcodeEntry {
        opcode: 0x11,
        kind: InstrKind::JpAbs,
        name: "JP_Abs",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg3],
    },
    OpcodeEntry {
        opcode: 0x12,
        kind: InstrKind::JpRel,
        name: "JP_Rel",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::ImmOffset],
    },
    OpcodeEntry {
        opcode: 0x13,
        kind: InstrKind::JpRel,
        name: "JP_Rel",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::ImmOffset],
    },
    OpcodeEntry {
        opcode: 0x14,
        kind: InstrKind::JpAbs,
        name: "JP_Abs",
        cond: Some("Z"),
        ops_reversed: None,
        operands: &[OperandKind::Imm(16)],
    },
    OpcodeEntry {
        opcode: 0x15,
        kind: InstrKind::JpAbs,
        name: "JP_Abs",
        cond: Some("NZ"),
        ops_reversed: None,
        operands: &[OperandKind::Imm(16)],
    },
    OpcodeEntry {
        opcode: 0x16,
        kind: InstrKind::JpAbs,
        name: "JP_Abs",
        cond: Some("C"),
        ops_reversed: None,
        operands: &[OperandKind::Imm(16)],
    },
    OpcodeEntry {
        opcode: 0x17,
        kind: InstrKind::JpAbs,
        name: "JP_Abs",
        cond: Some("NC"),
        ops_reversed: None,
        operands: &[OperandKind::Imm(16)],
    },
    OpcodeEntry {
        opcode: 0x18,
        kind: InstrKind::JpRel,
        name: "JP_Rel",
        cond: Some("Z"),
        ops_reversed: None,
        operands: &[OperandKind::ImmOffset],
    },
    OpcodeEntry {
        opcode: 0x19,
        kind: InstrKind::JpRel,
        name: "JP_Rel",
        cond: Some("Z"),
        ops_reversed: None,
        operands: &[OperandKind::ImmOffset],
    },
    OpcodeEntry {
        opcode: 0x1A,
        kind: InstrKind::JpRel,
        name: "JP_Rel",
        cond: Some("NZ"),
        ops_reversed: None,
        operands: &[OperandKind::ImmOffset],
    },
    OpcodeEntry {
        opcode: 0x1B,
        kind: InstrKind::JpRel,
        name: "JP_Rel",
        cond: Some("NZ"),
        ops_reversed: None,
        operands: &[OperandKind::ImmOffset],
    },
    OpcodeEntry {
        opcode: 0x1C,
        kind: InstrKind::JpRel,
        name: "JP_Rel",
        cond: Some("C"),
        ops_reversed: None,
        operands: &[OperandKind::ImmOffset],
    },
    OpcodeEntry {
        opcode: 0x1D,
        kind: InstrKind::JpRel,
        name: "JP_Rel",
        cond: Some("C"),
        ops_reversed: None,
        operands: &[OperandKind::ImmOffset],
    },
    OpcodeEntry {
        opcode: 0x1E,
        kind: InstrKind::JpRel,
        name: "JP_Rel",
        cond: Some("NC"),
        ops_reversed: None,
        operands: &[OperandKind::ImmOffset],
    },
    OpcodeEntry {
        opcode: 0x1F,
        kind: InstrKind::JpRel,
        name: "JP_Rel",
        cond: Some("NC"),
        ops_reversed: None,
        operands: &[OperandKind::ImmOffset],
    },
    OpcodeEntry {
        opcode: 0x20,
        kind: InstrKind::Unknown,
        name: "UnknownInstruction",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0x21,
        kind: InstrKind::Pre,
        name: "PRE",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0x22,
        kind: InstrKind::Pre,
        name: "PRE",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0x23,
        kind: InstrKind::Pre,
        name: "PRE",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0x24,
        kind: InstrKind::Pre,
        name: "PRE",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0x25,
        kind: InstrKind::Pre,
        name: "PRE",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0x26,
        kind: InstrKind::Pre,
        name: "PRE",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0x27,
        kind: InstrKind::Pre,
        name: "PRE",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0x28,
        kind: InstrKind::PushU,
        name: "PUSHU",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0x29,
        kind: InstrKind::PushU,
        name: "PUSHU",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegIL],
    },
    OpcodeEntry {
        opcode: 0x2A,
        kind: InstrKind::PushU,
        name: "PUSHU",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::BA, 16)],
    },
    OpcodeEntry {
        opcode: 0x2B,
        kind: InstrKind::PushU,
        name: "PUSHU",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::I, 16)],
    },
    OpcodeEntry {
        opcode: 0x2C,
        kind: InstrKind::PushU,
        name: "PUSHU",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::X, 24)],
    },
    OpcodeEntry {
        opcode: 0x2D,
        kind: InstrKind::PushU,
        name: "PUSHU",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::Y, 24)],
    },
    OpcodeEntry {
        opcode: 0x2E,
        kind: InstrKind::PushU,
        name: "PUSHU",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegF],
    },
    OpcodeEntry {
        opcode: 0x2F,
        kind: InstrKind::PushU,
        name: "PUSHU",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegIMR],
    },
    OpcodeEntry {
        opcode: 0x30,
        kind: InstrKind::Pre,
        name: "PRE",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0x31,
        kind: InstrKind::Pre,
        name: "PRE",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0x32,
        kind: InstrKind::Pre,
        name: "PRE",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0x33,
        kind: InstrKind::Pre,
        name: "PRE",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0x34,
        kind: InstrKind::Pre,
        name: "PRE",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0x35,
        kind: InstrKind::Pre,
        name: "PRE",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0x36,
        kind: InstrKind::Pre,
        name: "PRE",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0x37,
        kind: InstrKind::Pre,
        name: "PRE",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0x38,
        kind: InstrKind::PopU,
        name: "POPU",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0x39,
        kind: InstrKind::PopU,
        name: "POPU",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegIL],
    },
    OpcodeEntry {
        opcode: 0x3A,
        kind: InstrKind::PopU,
        name: "POPU",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::BA, 16)],
    },
    OpcodeEntry {
        opcode: 0x3B,
        kind: InstrKind::PopU,
        name: "POPU",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::I, 16)],
    },
    OpcodeEntry {
        opcode: 0x3C,
        kind: InstrKind::PopU,
        name: "POPU",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::X, 24)],
    },
    OpcodeEntry {
        opcode: 0x3D,
        kind: InstrKind::PopU,
        name: "POPU",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::Y, 24)],
    },
    OpcodeEntry {
        opcode: 0x3E,
        kind: InstrKind::PopU,
        name: "POPU",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegF],
    },
    OpcodeEntry {
        opcode: 0x3F,
        kind: InstrKind::PopU,
        name: "POPU",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegIMR],
    },
    OpcodeEntry {
        opcode: 0x40,
        kind: InstrKind::Add,
        name: "ADD",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x41,
        kind: InstrKind::Add,
        name: "ADD",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x42,
        kind: InstrKind::Add,
        name: "ADD",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8), OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0x43,
        kind: InstrKind::Add,
        name: "ADD",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0x44,
        kind: InstrKind::Add,
        name: "ADD",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegPair(2)],
    },
    OpcodeEntry {
        opcode: 0x45,
        kind: InstrKind::Add,
        name: "ADD",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegPair(3)],
    },
    OpcodeEntry {
        opcode: 0x46,
        kind: InstrKind::Add,
        name: "ADD",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegPair(1)],
    },
    OpcodeEntry {
        opcode: 0x47,
        kind: InstrKind::Pmdf,
        name: "PMDF",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x48,
        kind: InstrKind::Sub,
        name: "SUB",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x49,
        kind: InstrKind::Sub,
        name: "SUB",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x4A,
        kind: InstrKind::Sub,
        name: "SUB",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8), OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0x4B,
        kind: InstrKind::Sub,
        name: "SUB",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0x4C,
        kind: InstrKind::Sub,
        name: "SUB",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegPair(2)],
    },
    OpcodeEntry {
        opcode: 0x4D,
        kind: InstrKind::Sub,
        name: "SUB",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegPair(3)],
    },
    OpcodeEntry {
        opcode: 0x4E,
        kind: InstrKind::Sub,
        name: "SUB",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegPair(1)],
    },
    OpcodeEntry {
        opcode: 0x4F,
        kind: InstrKind::PushS,
        name: "PUSHS",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegF],
    },
    OpcodeEntry {
        opcode: 0x50,
        kind: InstrKind::Adc,
        name: "ADC",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x51,
        kind: InstrKind::Adc,
        name: "ADC",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x52,
        kind: InstrKind::Adc,
        name: "ADC",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8), OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0x53,
        kind: InstrKind::Adc,
        name: "ADC",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0x54,
        kind: InstrKind::Adc,
        name: "ADCL",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0x55,
        kind: InstrKind::Adc,
        name: "ADCL",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0x56,
        kind: InstrKind::Mvl,
        name: "MVL",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegIMemOffset(RegImemOffsetKind::DestImem)],
    },
    OpcodeEntry {
        opcode: 0x57,
        kind: InstrKind::Pmdf,
        name: "PMDF",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0x58,
        kind: InstrKind::Sbc,
        name: "SBC",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x59,
        kind: InstrKind::Sbc,
        name: "SBC",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x5A,
        kind: InstrKind::Sbc,
        name: "SBC",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8), OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0x5B,
        kind: InstrKind::Sbc,
        name: "SBC",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0x5C,
        kind: InstrKind::Sbcl,
        name: "SBCL",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0x5D,
        kind: InstrKind::Sbcl,
        name: "SBCL",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0x5E,
        kind: InstrKind::Mvl,
        name: "MVL",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegIMemOffset(RegImemOffsetKind::DestRegOffset)],
    },
    OpcodeEntry {
        opcode: 0x5F,
        kind: InstrKind::PopS,
        name: "POPS",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegF],
    },
    OpcodeEntry {
        opcode: 0x60,
        kind: InstrKind::Cmp,
        name: "CMP",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x61,
        kind: InstrKind::Cmp,
        name: "CMP",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x62,
        kind: InstrKind::Cmp,
        name: "CMP",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemAddrWidth(1), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x63,
        kind: InstrKind::Cmp,
        name: "CMP",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0x64,
        kind: InstrKind::Test,
        name: "TEST",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x65,
        kind: InstrKind::Test,
        name: "TEST",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x66,
        kind: InstrKind::Test,
        name: "TEST",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemAddrWidth(1), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x67,
        kind: InstrKind::Test,
        name: "TEST",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0x68,
        kind: InstrKind::Xor,
        name: "XOR",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x69,
        kind: InstrKind::Xor,
        name: "XOR",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x6A,
        kind: InstrKind::Xor,
        name: "XOR",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemAddrWidth(1), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x6B,
        kind: InstrKind::Xor,
        name: "XOR",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0x6C,
        kind: InstrKind::Inc,
        name: "INC",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg3],
    },
    OpcodeEntry {
        opcode: 0x6D,
        kind: InstrKind::Inc,
        name: "INC",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0x6E,
        kind: InstrKind::Xor,
        name: "XOR",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0x6F,
        kind: InstrKind::Xor,
        name: "XOR",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8), OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0x70,
        kind: InstrKind::And,
        name: "AND",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x71,
        kind: InstrKind::And,
        name: "AND",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x72,
        kind: InstrKind::And,
        name: "AND",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemAddrWidth(1), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x73,
        kind: InstrKind::And,
        name: "AND",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0x74,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8), OperandKind::RegB],
    },
    OpcodeEntry {
        opcode: 0x75,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegB, OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0x76,
        kind: InstrKind::And,
        name: "AND",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0x77,
        kind: InstrKind::And,
        name: "AND",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8), OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0x78,
        kind: InstrKind::Or,
        name: "OR",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x79,
        kind: InstrKind::Or,
        name: "OR",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x7A,
        kind: InstrKind::Or,
        name: "OR",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemAddrWidth(1), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0x7B,
        kind: InstrKind::Or,
        name: "OR",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0x7C,
        kind: InstrKind::Dec,
        name: "DEC",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg3],
    },
    OpcodeEntry {
        opcode: 0x7D,
        kind: InstrKind::Dec,
        name: "DEC",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0x7E,
        kind: InstrKind::Or,
        name: "OR",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0x7F,
        kind: InstrKind::Or,
        name: "OR",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8), OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0x80,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8), OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0x81,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegIL, OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0x82,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::BA, 16), OperandKind::IMem(16)],
    },
    OpcodeEntry {
        opcode: 0x83,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::I, 16), OperandKind::IMem(16)],
    },
    OpcodeEntry {
        opcode: 0x84,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::X, 24), OperandKind::IMem(20)],
    },
    OpcodeEntry {
        opcode: 0x85,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::Y, 24), OperandKind::IMem(20)],
    },
    OpcodeEntry {
        opcode: 0x86,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::U, 24), OperandKind::IMem(20)],
    },
    OpcodeEntry {
        opcode: 0x87,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::S, 24), OperandKind::IMem(20)],
    },
    OpcodeEntry {
        opcode: 0x88,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8), OperandKind::EMemAddrWidth(1)],
    },
    OpcodeEntry {
        opcode: 0x89,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegIL, OperandKind::EMemAddrWidth(1)],
    },
    OpcodeEntry {
        opcode: 0x8A,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::BA, 16), OperandKind::EMemAddrWidth(2)],
    },
    OpcodeEntry {
        opcode: 0x8B,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::I, 16), OperandKind::EMemAddrWidth(2)],
    },
    OpcodeEntry {
        opcode: 0x8C,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::X, 24), OperandKind::EMemAddrWidth(3)],
    },
    OpcodeEntry {
        opcode: 0x8D,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::Y, 24), OperandKind::EMemAddrWidth(3)],
    },
    OpcodeEntry {
        opcode: 0x8E,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::U, 24), OperandKind::EMemAddrWidth(3)],
    },
    OpcodeEntry {
        opcode: 0x8F,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::S, 24), OperandKind::EMemAddrWidth(3)],
    },
    OpcodeEntry {
        opcode: 0x90,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8), OperandKind::EMemRegWidth(1)],
    },
    OpcodeEntry {
        opcode: 0x91,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegIL, OperandKind::EMemRegWidth(1)],
    },
    OpcodeEntry {
        opcode: 0x92,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::BA, 16), OperandKind::EMemRegWidth(2)],
    },
    OpcodeEntry {
        opcode: 0x93,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::I, 16), OperandKind::EMemRegWidth(2)],
    },
    OpcodeEntry {
        opcode: 0x94,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::X, 24), OperandKind::EMemRegWidth(3)],
    },
    OpcodeEntry {
        opcode: 0x95,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::Y, 24), OperandKind::EMemRegWidth(3)],
    },
    OpcodeEntry {
        opcode: 0x96,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::U, 24), OperandKind::EMemRegWidth(3)],
    },
    OpcodeEntry {
        opcode: 0x97,
        kind: InstrKind::Sc,
        name: "SC",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0x98,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8), OperandKind::EMemIMemWidth(1)],
    },
    OpcodeEntry {
        opcode: 0x99,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegIL, OperandKind::EMemIMemWidth(1)],
    },
    OpcodeEntry {
        opcode: 0x9A,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::BA, 16), OperandKind::EMemIMemWidth(1)],
    },
    OpcodeEntry {
        opcode: 0x9B,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::I, 16), OperandKind::EMemIMemWidth(1)],
    },
    OpcodeEntry {
        opcode: 0x9C,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::X, 24), OperandKind::EMemIMemWidth(1)],
    },
    OpcodeEntry {
        opcode: 0x9D,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::Y, 24), OperandKind::EMemIMemWidth(1)],
    },
    OpcodeEntry {
        opcode: 0x9E,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::U, 24), OperandKind::EMemIMemWidth(1)],
    },
    OpcodeEntry {
        opcode: 0x9F,
        kind: InstrKind::Rc,
        name: "RC",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0xA0,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0xA1,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::RegIL],
    },
    OpcodeEntry {
        opcode: 0xA2,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(16), OperandKind::Reg(RegName::BA, 16)],
    },
    OpcodeEntry {
        opcode: 0xA3,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(16), OperandKind::Reg(RegName::I, 16)],
    },
    OpcodeEntry {
        opcode: 0xA4,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(20), OperandKind::Reg(RegName::X, 24)],
    },
    OpcodeEntry {
        opcode: 0xA5,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(20), OperandKind::Reg(RegName::Y, 24)],
    },
    OpcodeEntry {
        opcode: 0xA6,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(20), OperandKind::Reg(RegName::U, 24)],
    },
    OpcodeEntry {
        opcode: 0xA7,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(20), OperandKind::Reg(RegName::S, 24)],
    },
    OpcodeEntry {
        opcode: 0xA8,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemAddrWidth(1), OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0xA9,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemAddrWidth(1), OperandKind::RegIL],
    },
    OpcodeEntry {
        opcode: 0xAA,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemAddrWidth(2), OperandKind::Reg(RegName::BA, 16)],
    },
    OpcodeEntry {
        opcode: 0xAB,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemAddrWidth(2), OperandKind::Reg(RegName::I, 16)],
    },
    OpcodeEntry {
        opcode: 0xAC,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemAddrWidth(3), OperandKind::Reg(RegName::X, 24)],
    },
    OpcodeEntry {
        opcode: 0xAD,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemAddrWidth(3), OperandKind::Reg(RegName::Y, 24)],
    },
    OpcodeEntry {
        opcode: 0xAE,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemAddrWidth(3), OperandKind::Reg(RegName::U, 24)],
    },
    OpcodeEntry {
        opcode: 0xAF,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemAddrWidth(3), OperandKind::Reg(RegName::S, 24)],
    },
    OpcodeEntry {
        opcode: 0xB0,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemRegWidth(1), OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0xB1,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemRegWidth(1), OperandKind::RegIL],
    },
    OpcodeEntry {
        opcode: 0xB2,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemRegWidth(2), OperandKind::Reg(RegName::BA, 16)],
    },
    OpcodeEntry {
        opcode: 0xB3,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemRegWidth(2), OperandKind::Reg(RegName::I, 16)],
    },
    OpcodeEntry {
        opcode: 0xB4,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemRegWidth(3), OperandKind::Reg(RegName::X, 24)],
    },
    OpcodeEntry {
        opcode: 0xB5,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemRegWidth(3), OperandKind::Reg(RegName::Y, 24)],
    },
    OpcodeEntry {
        opcode: 0xB6,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemRegWidth(3), OperandKind::Reg(RegName::U, 24)],
    },
    OpcodeEntry {
        opcode: 0xB7,
        kind: InstrKind::Cmp,
        name: "CMP",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0xB8,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemIMemWidth(1), OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0xB9,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemIMemWidth(1), OperandKind::RegIL],
    },
    OpcodeEntry {
        opcode: 0xBA,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemIMemWidth(1), OperandKind::Reg(RegName::BA, 16)],
    },
    OpcodeEntry {
        opcode: 0xBB,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemIMemWidth(1), OperandKind::Reg(RegName::I, 16)],
    },
    OpcodeEntry {
        opcode: 0xBC,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemIMemWidth(1), OperandKind::Reg(RegName::X, 24)],
    },
    OpcodeEntry {
        opcode: 0xBD,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemIMemWidth(1), OperandKind::Reg(RegName::Y, 24)],
    },
    OpcodeEntry {
        opcode: 0xBE,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemIMemWidth(1), OperandKind::Reg(RegName::U, 24)],
    },
    OpcodeEntry {
        opcode: 0xBF,
        kind: InstrKind::Unknown,
        name: "UnknownInstruction",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0xC0,
        kind: InstrKind::Ex,
        name: "EX",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0xC1,
        kind: InstrKind::Ex,
        name: "EXW",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(16), OperandKind::IMem(16)],
    },
    OpcodeEntry {
        opcode: 0xC2,
        kind: InstrKind::Ex,
        name: "EXP",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(20), OperandKind::IMem(20)],
    },
    OpcodeEntry {
        opcode: 0xC3,
        kind: InstrKind::Exl,
        name: "EXL",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0xC4,
        kind: InstrKind::Dadl,
        name: "DADL",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0xC5,
        kind: InstrKind::Dadl,
        name: "DADL",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0xC6,
        kind: InstrKind::Cmpw,
        name: "CMPW",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(16), OperandKind::IMem(16)],
    },
    OpcodeEntry {
        opcode: 0xC7,
        kind: InstrKind::Cmpp,
        name: "CMPP",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(20), OperandKind::IMem(20)],
    },
    OpcodeEntry {
        opcode: 0xC8,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0xC9,
        kind: InstrKind::Mvw,
        name: "MVW",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(16), OperandKind::IMem(16)],
    },
    OpcodeEntry {
        opcode: 0xCA,
        kind: InstrKind::Mvp,
        name: "MVP",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(20), OperandKind::IMem(20)],
    },
    OpcodeEntry {
        opcode: 0xCB,
        kind: InstrKind::Mvl,
        name: "MVL",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0xCC,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Imm(8)],
    },
    OpcodeEntry {
        opcode: 0xCD,
        kind: InstrKind::Mvw,
        name: "MVW",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(16), OperandKind::Imm(16)],
    },
    OpcodeEntry {
        opcode: 0xCE,
        kind: InstrKind::Tcl,
        name: "TCL",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0xCF,
        kind: InstrKind::Mvld,
        name: "MVLD",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0xD0,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::EMemAddrWidth(1)],
    },
    OpcodeEntry {
        opcode: 0xD1,
        kind: InstrKind::Mvw,
        name: "MVW",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(16), OperandKind::EMemAddrWidth(2)],
    },
    OpcodeEntry {
        opcode: 0xD2,
        kind: InstrKind::Mvp,
        name: "MVP",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(20), OperandKind::EMemAddrWidth(3)],
    },
    OpcodeEntry {
        opcode: 0xD3,
        kind: InstrKind::Mvl,
        name: "MVL",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::EMemAddrWidth(1)],
    },
    OpcodeEntry {
        opcode: 0xD4,
        kind: InstrKind::Dsbl,
        name: "DSBL",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0xD5,
        kind: InstrKind::Dsbl,
        name: "DSBL",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8), OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0xD6,
        kind: InstrKind::Cmpw,
        name: "CMPW",
        cond: None,
        ops_reversed: Some(true),
        operands: &[OperandKind::IMem(16), OperandKind::Reg3],
    },
    OpcodeEntry {
        opcode: 0xD7,
        kind: InstrKind::Cmpp,
        name: "CMPP",
        cond: None,
        ops_reversed: Some(true),
        operands: &[OperandKind::IMem(20), OperandKind::Reg3],
    },
    OpcodeEntry {
        opcode: 0xD8,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemAddrWidth(1), OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0xD9,
        kind: InstrKind::Mvw,
        name: "MVW",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemAddrWidth(2), OperandKind::IMem(16)],
    },
    OpcodeEntry {
        opcode: 0xDA,
        kind: InstrKind::Mvp,
        name: "MVP",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemAddrWidth(3), OperandKind::IMem(20)],
    },
    OpcodeEntry {
        opcode: 0xDB,
        kind: InstrKind::Mvl,
        name: "MVL",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemAddrWidth(1), OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0xDC,
        kind: InstrKind::Mvp,
        name: "MVP",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(20), OperandKind::Imm(20)],
    },
    OpcodeEntry {
        opcode: 0xDD,
        kind: InstrKind::Ex,
        name: "EX",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8), OperandKind::RegB],
    },
    OpcodeEntry {
        opcode: 0xDE,
        kind: InstrKind::Halt,
        name: "HALT",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0xDF,
        kind: InstrKind::Off,
        name: "OFF",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0xE0,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegIMemOffset(RegImemOffsetKind::DestImem)],
    },
    OpcodeEntry {
        opcode: 0xE1,
        kind: InstrKind::Mvw,
        name: "MVW",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegIMemOffset(RegImemOffsetKind::DestImem)],
    },
    OpcodeEntry {
        opcode: 0xE2,
        kind: InstrKind::Mvp,
        name: "MVP",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegIMemOffset(RegImemOffsetKind::DestImem)],
    },
    OpcodeEntry {
        opcode: 0xE3,
        kind: InstrKind::Mvl,
        name: "MVL",
        cond: None,
        ops_reversed: Some(true),
        operands: &[OperandKind::IMem(8), OperandKind::EMemRegModePostPre],
    },
    OpcodeEntry {
        opcode: 0xE4,
        kind: InstrKind::Ror,
        name: "ROR",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0xE5,
        kind: InstrKind::Ror,
        name: "ROR",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0xE6,
        kind: InstrKind::Rol,
        name: "ROL",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0xE7,
        kind: InstrKind::Rol,
        name: "ROL",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0xE8,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegIMemOffset(RegImemOffsetKind::DestRegOffset)],
    },
    OpcodeEntry {
        opcode: 0xE9,
        kind: InstrKind::Mvw,
        name: "MVW",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegIMemOffset(RegImemOffsetKind::DestRegOffset)],
    },
    OpcodeEntry {
        opcode: 0xEA,
        kind: InstrKind::Mvp,
        name: "MVP",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegIMemOffset(RegImemOffsetKind::DestRegOffset)],
    },
    OpcodeEntry {
        opcode: 0xEB,
        kind: InstrKind::Mvl,
        name: "MVL",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemRegWidth(1), OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0xEC,
        kind: InstrKind::Dsll,
        name: "DSLL",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0xED,
        kind: InstrKind::Ex,
        name: "EX",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegPair(2)],
    },
    OpcodeEntry {
        opcode: 0xEE,
        kind: InstrKind::Swap,
        name: "SWAP",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0xEF,
        kind: InstrKind::Wait,
        name: "WAIT",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0xF0,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemImemOffsetDestIntMem],
    },
    OpcodeEntry {
        opcode: 0xF1,
        kind: InstrKind::Mvw,
        name: "MVW",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemImemOffsetDestIntMem],
    },
    OpcodeEntry {
        opcode: 0xF2,
        kind: InstrKind::Mvp,
        name: "MVP",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemImemOffsetDestIntMem],
    },
    OpcodeEntry {
        opcode: 0xF3,
        kind: InstrKind::Mvl,
        name: "MVL",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemImemOffsetDestIntMem],
    },
    OpcodeEntry {
        opcode: 0xF4,
        kind: InstrKind::Shr,
        name: "SHR",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0xF5,
        kind: InstrKind::Shr,
        name: "SHR",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0xF6,
        kind: InstrKind::Shl,
        name: "SHL",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::Reg(RegName::A, 8)],
    },
    OpcodeEntry {
        opcode: 0xF7,
        kind: InstrKind::Shl,
        name: "SHL",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0xF8,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemImemOffsetDestExtMem],
    },
    OpcodeEntry {
        opcode: 0xF9,
        kind: InstrKind::Mvw,
        name: "MVW",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemImemOffsetDestExtMem],
    },
    OpcodeEntry {
        opcode: 0xFA,
        kind: InstrKind::Mvp,
        name: "MVP",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemImemOffsetDestExtMem],
    },
    OpcodeEntry {
        opcode: 0xFB,
        kind: InstrKind::Mvl,
        name: "MVL",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::EMemImemOffsetDestExtMem],
    },
    OpcodeEntry {
        opcode: 0xFC,
        kind: InstrKind::Dsrl,
        name: "DSRL",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::IMem(8)],
    },
    OpcodeEntry {
        opcode: 0xFD,
        kind: InstrKind::Mv,
        name: "MV",
        cond: None,
        ops_reversed: None,
        operands: &[OperandKind::RegPair(2)],
    },
    OpcodeEntry {
        opcode: 0xFE,
        kind: InstrKind::Ir,
        name: "IR",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
    OpcodeEntry {
        opcode: 0xFF,
        kind: InstrKind::Reset,
        name: "RESET",
        cond: None,
        ops_reversed: None,
        operands: &[],
    },
];
