import { test, expect, type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

async function prepare(page: Page, model: string) {
	// Deliberately synthetic, same actual WASM/worker code. Not real-app evidence.
	const rom = await readFile(resolve(process.cwd(), 'emulator-wasm/testdata/pf1_demo_rom_window.rom'));
	await page.route(`**/api/rom?model=${model}`, (route) => route.fulfill({ status: 200, body: rom }));
	await page.addInitScript((value) => localStorage.setItem('sc62015:rom-model', value), model);
	await page.goto('/');
	await expect(page.getByRole('button', { name: 'Step 20k' })).toBeEnabled();
	await page.getByTestId('fnr-panel').evaluate((element: HTMLDetailsElement) => { element.open = true; });
}

for (const model of ['pc-e500', 'iq-7000']) {
	for (const kind of ['script', 'stub', 'probe', 'trace']) {
		test(`${model}: Stop terminates an infinite ${kind} without losing the machine`, async ({ page }, info) => {
			await prepare(page, model);
			expect(await page.evaluate(() => crossOriginIsolated)).toBe(true);
			const loop = 'e.print("entered loop"); while (true) {}';
			const call = 'await e.call(0xB8000, { S: 0xB9003, IMR: 0 }, { maxInstructions: 100, trace: true });';
			const body = kind === 'stub' ? `e.stub(0xB8000, 'loop', () => { ${loop} }); ${call}` :
				kind === 'probe' ? `await e.withProbe(0xB8000, () => { ${loop} }, async () => { ${call} });` :
				kind === 'trace' ? `await e.perfetto.trace('loop', async () => { await e.step(1); ${loop} });` : loop;
			await page.getByTestId('fnr-editor').fill(`
await e.reset({ warmupTicks: 0 });
await e.memory.write(0xB8100, 1, 0x42);
await e.memory.write(0xB9000, 3, 0xC3B2A1);
await e.memory.write(0xB8000, 1, 0x07); // real RETF for probe fixture
${body}
`);
			await page.getByTestId('fnr-run').click();
			// This notification is generated by a real RPC from inside the loop's
			// scope, not merely the UI accepting Run or an arbitrary sleep.
			await expect(page.getByTestId('execution-progress')).toContainText('Isolated script: print');
			const start = Date.now();
			await page.getByRole('button', { name: 'Stop', exact: true }).click();
			await expect(page.getByTestId('emu-status')).toContainText(/STOPPED|HALTED/);
			await expect(page.getByTestId('fnr-run')).toBeEnabled();
			const elapsed = Date.now() - start;
			console.log(JSON.stringify({ model, kind, clickToStoppedUiMs: elapsed }));
			await info.attach('script-stop.json', { body: JSON.stringify({ model, kind, elapsedMs: elapsed,
				scope: 'Browser click plus acknowledged Stop and UI settlement; synthetic fixture, not hardware latency' }), contentType: 'application/json' });
			await expect(page.getByTestId('fnr-error')).toContainText('cancelled');
			if (kind === 'stub' || kind === 'probe') {
				await expect(page.getByTestId('fnr-call')).toHaveCount(1);
				await expect(page.getByTestId('fnr-call')).toContainText(kind === 'stub' ? 'cancelled' : 'returned');
			}
			await page.getByTestId('fnr-editor').fill(`
e.assert(await e.memory.read(0xB8100) === 0x42, 'machine RAM must survive Stop');
e.assert(await e.memory.read(0xB9000, 3) === 0xC3B2A1, 'debugger stack must be restored');
await e.perfetto.trace('after-stop', async () => { await e.step(1); });
return e.reg(Reg.PC);
`);
			await page.getByTestId('fnr-run').click();
			await expect(page.getByTestId('fnr-run')).toBeEnabled();
			await expect(page.getByTestId('fnr-error')).toHaveCount(0);
		});
	}
}

test('isolated callbacks preserve closures, ordering and live register reads', async ({ page }) => {
	await prepare(page, 'pc-e500');
	await page.getByTestId('fnr-editor').fill(`
await e.reset({ warmupTicks: 0 });
let hits = 0;
e.stub(0xB8000, 'patch', (mem) => ({ regs: { A: mem.read8(0xB8100) }, ret: { kind: 'retf' } }));
await e.memory.write(0xB8100, 1, 42);
const returned = await e.withProbe(0xB8000, (sample) => { hits++; e.assert(sample.count === 1); }, async () => {
  const call = await e.call(0xB8000, { S: 0xB9003 }, { trace: true });
  return call.artifacts.result.reason;
});
e.assert(hits === 1 && returned === 'returned');
e.assert(e.reg(Reg.A) === 42);
e.assert(e.calls.length === 1 && e.last().artifacts.result.reason === 'returned');
const snapshot = e.calls; snapshot.length = 0;
e.assert(e.calls.length === 1, 'artifact reads are copies');
return (await e.lcd.capture()).pixels.length;
`);
	await page.getByTestId('fnr-run').click();
	await expect(page.getByTestId('fnr-run')).toBeEnabled();
	await expect(page.getByTestId('fnr-error')).toHaveCount(0);
	await expect(page.getByTestId('fnr-call')).toHaveCount(1);
});

test('hosts without isolation headers refuse scripts without changing machine state', async ({ page }) => {
	await page.route('**/*', async (route) => {
		const response = await route.fetch();
		const headers = response.headers();
		delete headers['cross-origin-opener-policy'];
		delete headers['cross-origin-embedder-policy'];
		await route.fulfill({ response, headers });
	});
	await prepare(page, 'pc-e500');
	const before = await page.getByTestId('emu-status').textContent();
	await page.getByTestId('fnr-editor').fill('await e.step(1000);');
	await page.getByTestId('fnr-run').click();
	await expect(page.getByTestId('fnr-run')).toBeEnabled();
	await expect(page.getByTestId('fnr-error')).toContainText('requires cross-origin isolated workers');
	await expect(page.getByTestId('emu-status')).toHaveText(before!);
});

test('a pending step rejects overlapping mutations and drains before Stop', async ({ page }) => {
	await prepare(page, 'pc-e500');
	await page.getByTestId('fnr-editor').fill(`
await e.memory.write(0xB8100, 1, 42);
const stepping = e.step(4_000_000_000);
let rejected = false;
try { await e.memory.write(0xB8100, 1, 99); }
catch (error) { rejected = String(error).includes('Await the active machine operation'); }
e.assert(rejected, 'concurrent writes must not interleave with execution');
e.print('mutation rejected');
await stepping;
`);
	await page.getByTestId('fnr-run').click();
	await expect(page.getByTestId('execution-progress')).toContainText('Isolated script: print');
	await page.getByRole('button', { name: 'Stop', exact: true }).click();
	await expect(page.getByTestId('fnr-run')).toBeEnabled();
	await expect(page.getByTestId('fnr-error')).toContainText('Execution cancelled');
	await page.getByTestId('fnr-editor').fill("e.assert(await e.memory.read(0xB8100) === 42); await e.step(1);");
	await page.getByTestId('fnr-run').click();
	await expect(page.getByTestId('fnr-run')).toBeEnabled();
	await expect(page.getByTestId('fnr-error')).toHaveCount(0);
});
