from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

from scil_codegen_manifest import generate_manifest  # type: ignore

ROOT = Path(__file__).resolve().parents[1]
GENERATED_DIR = ROOT / "sc62015" / "rustcore" / "generated"


def _write_manifest(entries, path: Path) -> None:
    path.write_text(json.dumps(entries, indent=2) + "\n", encoding="utf-8")


def _write_handlers(entries, path: Path) -> None:
    header = """// @generated by tools/scil_codegen_rust.py; do not edit.
#[allow(dead_code)]
pub const PAYLOAD: &str = r#"
"""
    payload = json.dumps(entries, indent=2)
    path.write_text(f"{header}{payload}\n\"#;\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Rust stubs from SCIL manifest")
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=GENERATED_DIR,
        help="Directory to place generated artifacts",
    )
    args = parser.parse_args()

    manifest, errors = generate_manifest()
    if errors:
        print(
            "Warning: manifest generation reported issues:\n"
            + "\n".join(f"  opcode 0x{op:02X}: {msg}" for op, msg in errors),
            file=sys.stderr,
        )

    args.out_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = args.out_dir / "manifest.json"
    handlers_path = args.out_dir / "handlers.rs"
    _write_manifest(manifest, manifest_path)
    _write_handlers(manifest, handlers_path)
    manifest_path.chmod(0o644)
    handlers_path.chmod(0o644)
    print(f"Generated {len(manifest)} entries into {args.out_dir}")


if __name__ == "__main__":
    main()
